CREATE TABLE mytable(
   Number                                    INTEGER  NOT NULL PRIMARY KEY 
  ,Name                                      VARCHAR(44) NOT NULL
  ,City                                      VARCHAR(7) NOT NULL
  ,District                                  VARCHAR(20)
  ,Placement_fee_or_Application_Entrance     INTEGER 
  ,Course_fee                                INTEGER 
  ,Residence_type                            VARCHAR(17)
  ,Residence_fee_course_duration             INTEGER 
  ,Total_fee                                 INTEGER 
  ,Duration_Months                           NUMERIC(4,1)
  ,Total_fee_per_month                       NUMERIC(9,2)
  ,Cost_per_month_in_Euro                    NUMERIC(7,2)
  ,Website                                   VARCHAR(41)
  ,Commentary                                VARCHAR(14)
);
INSERT INTO mytable(Number,Name,City,District,Placement_fee_or_Application_Entrance,Course_fee,Residence_type,Residence_fee_course_duration,Total_fee,Duration_Months,Total_fee_per_month,Cost_per_month_in_Euro,Website,Commentary) VALUES (1,'Genki Japanese & culture school-Yokohama','Fukuoka',NULL,9500,990000,'Private',765000,1764500,11.5,153434.78,1168.67,'http://genkijacs.com/',NULL);
INSERT INTO mytable(Number,Name,City,District,Placement_fee_or_Application_Entrance,Course_fee,Residence_type,Residence_fee_course_duration,Total_fee,Duration_Months,Total_fee_per_month,Cost_per_month_in_Euro,Website,Commentary) VALUES (2,'Tokyo Central Japanese Language School','Tokyo','Shinjuku',60000,736000,'Non-Inclued',0,796000,12.0,NULL,NULL,'https://tcj-nihongo.co.jp/en/',NULL);
INSERT INTO mytable(Number,Name,City,District,Placement_fee_or_Application_Entrance,Course_fee,Residence_type,Residence_fee_course_duration,Total_fee,Duration_Months,Total_fee_per_month,Cost_per_month_in_Euro,Website,Commentary) VALUES (3,'KAI Japanese language School','Tokyo','Shin-Obuko',30000,902000,'Share House',432000,1364000,12.0,113666.67,865.77,'http://en.kaij.jp/',NULL);
INSERT INTO mytable(Number,Name,City,District,Placement_fee_or_Application_Entrance,Course_fee,Residence_type,Residence_fee_course_duration,Total_fee,Duration_Months,Total_fee_per_month,Cost_per_month_in_Euro,Website,Commentary) VALUES (4,'ISI Japanese Language School -Tokyo','Tokyo','Takanobaba/Ikebukuro',77000,746000,'Student',1184000,2007000,12.0,167250.00,1273.90,'http://www.isi-education.com/',NULL);
INSERT INTO mytable(Number,Name,City,District,Placement_fee_or_Application_Entrance,Course_fee,Residence_type,Residence_fee_course_duration,Total_fee,Duration_Months,Total_fee_per_month,Cost_per_month_in_Euro,Website,Commentary) VALUES (5,'ISI Japanese Language School - Kyoto','Kyoto',NULL,77000,746000,'Student',1040000,1863000,12.0,155250.00,1182.50,'http://www.isi-education.com/',NULL);
INSERT INTO mytable(Number,Name,City,District,Placement_fee_or_Application_Entrance,Course_fee,Residence_type,Residence_fee_course_duration,Total_fee,Duration_Months,Total_fee_per_month,Cost_per_month_in_Euro,Website,Commentary) VALUES (6,'ISI Japanese Language School -Nagano','Nagano',NULL,77000,686000,'Student',690000,1453000,9.2,157934.78,1202.95,'http://www.isi-education.com/',NULL);
INSERT INTO mytable(Number,Name,City,District,Placement_fee_or_Application_Entrance,Course_fee,Residence_type,Residence_fee_course_duration,Total_fee,Duration_Months,Total_fee_per_month,Cost_per_month_in_Euro,Website,Commentary) VALUES (7,'Kudan Institute of Japanese Language&Culture','Tokyo','Chiyoda',20000,805000,'Homestay',780000,1605000,12.0,133750.00,1018.74,'https://www.kudan-japanese-school.com/',NULL);
INSERT INTO mytable(Number,Name,City,District,Placement_fee_or_Application_Entrance,Course_fee,Residence_type,Residence_fee_course_duration,Total_fee,Duration_Months,Total_fee_per_month,Cost_per_month_in_Euro,Website,Commentary) VALUES (8,'NIHON KOGAKUIN JAPANESE LANGUAGE SCHOOL','Tokyo','Kamata',100000,990000,'Dormitory',NULL,1090000,18.0,NULL,NULL,'http://www.jst.ac.jp/us/index.html','By go go Nihon');
INSERT INTO mytable(Number,Name,City,District,Placement_fee_or_Application_Entrance,Course_fee,Residence_type,Residence_fee_course_duration,Total_fee,Duration_Months,Total_fee_per_month,Cost_per_month_in_Euro,Website,Commentary) VALUES (9,'Akamonkai','Tokyo','Nippori',128000,960000,'Private Dormitory',NULL,1088000,18.0,NULL,NULL,'https://www.akamonkai.ac.jp/english/',NULL);
INSERT INTO mytable(Number,Name,City,District,Placement_fee_or_Application_Entrance,Course_fee,Residence_type,Residence_fee_course_duration,Total_fee,Duration_Months,Total_fee_per_month,Cost_per_month_in_Euro,Website,Commentary) VALUES (10,'EF Education first Tokyo','Tokyo','Shibuya',NULL,NULL,'Homestay',NULL,2733458,9.0,303717.53,2313.33,'https://www.ef.com/wwfr/',NULL);
INSERT INTO mytable(Number,Name,City,District,Placement_fee_or_Application_Entrance,Course_fee,Residence_type,Residence_fee_course_duration,Total_fee,Duration_Months,Total_fee_per_month,Cost_per_month_in_Euro,Website,Commentary) VALUES (11,'Intercultural Institute of Japan','Tokyo','Akihabara',80000,1128800,'Student',1278000,2486800,18.0,138155.56,1052.29,'http://www.incul.com/eng/japanese_school/',NULL);
INSERT INTO mytable(Number,Name,City,District,Placement_fee_or_Application_Entrance,Course_fee,Residence_type,Residence_fee_course_duration,Total_fee,Duration_Months,Total_fee_per_month,Cost_per_month_in_Euro,Website,Commentary) VALUES (12,'Kyoto Minsai Japanese Language School','Kyoto',NULL,86000,882000,'Dormitory',648000,1616000,18.0,89777.78,683.81,'http://www.kyotominsai.co.jp/english/',NULL);
INSERT INTO mytable(Number,Name,City,District,Placement_fee_or_Application_Entrance,Course_fee,Residence_type,Residence_fee_course_duration,Total_fee,Duration_Months,Total_fee_per_month,Cost_per_month_in_Euro,Website,Commentary) VALUES (13,'ECC Japanese language institute','Nagoya',NULL,71000,985000,'Dormitory',932200,1988200,18.0,110455.56,841.31,'http://ecc-nihongo.com/en/nagoya/',NULL);
INSERT INTO mytable(Number,Name,City,District,Placement_fee_or_Application_Entrance,Course_fee,Residence_type,Residence_fee_course_duration,Total_fee,Duration_Months,Total_fee_per_month,Cost_per_month_in_Euro,Website,Commentary) VALUES (14,'Nagoya international Academy','Nagoya',NULL,118000,1033840,NULL,NULL,NULL,18.0,NULL,NULL,NULL,NULL);
INSERT INTO mytable(Number,Name,City,District,Placement_fee_or_Application_Entrance,Course_fee,Residence_type,Residence_fee_course_duration,Total_fee,Duration_Months,Total_fee_per_month,Cost_per_month_in_Euro,Website,Commentary) VALUES (15,'JCLI Japanese Language School','Tokyo','Kita',75600,712800,NULL,NULL,NULL,NULL,NULL,NULL,'http://en.jclischool.com/',NULL);
INSERT INTO mytable(Number,Name,City,District,Placement_fee_or_Application_Entrance,Course_fee,Residence_type,Residence_fee_course_duration,Total_fee,Duration_Months,Total_fee_per_month,Cost_per_month_in_Euro,Website,Commentary) VALUES (16,'Nihongo Center','Kyoto',NULL,86400,648000,NULL,NULL,NULL,12.0,NULL,NULL,NULL,NULL);
INSERT INTO mytable(Number,Name,City,District,Placement_fee_or_Application_Entrance,Course_fee,Residence_type,Residence_fee_course_duration,Total_fee,Duration_Months,Total_fee_per_month,Cost_per_month_in_Euro,Website,Commentary) VALUES (17,'Shinjuku Japanese Language Institute','Tokyo','Shinjuku',70000,1095800,'Student',972000,2137800,18.0,118766.67,904.61,'https://www.sng.ac.jp/en/',NULL);
